export const courseSource = 'eBook 1 - Artisan Perfumery.pdf';
// Read from the supplied DOCX transcript and checked against its course structure.
// These are edited study notes, not a verbatim transcript or product certification.
export const lessons = [
  {id:'practice',title:'The perfumer’s work',group:'Getting started',pages:[6,7],summary:'Build your skills through observation, repeated trials and a clear creative brief.',blocks:[
    ['Learning through practice','The course treats perfumery as a combination of theory, creativity and repeated hands-on work. Learning the vocabulary helps you describe a scent; working with the materials helps you recognize it. A successful first blend is a starting point for further trials.'],
    ['A useful practice cycle','Study a small number of materials, describe them in your own words, make a small trial, record the exact quantities, then revisit the result. Keep both successful and unsuccessful versions so you can understand what changed.'],
    ['A brief before a blend','Describe the person or occasion, the mood, and the setting you imagine. Choose a few words such as bright, dry, soft, green or warm. Use those words to guide your ingredient choices and later evaluation.']],exercise:'Write a three-sentence brief for your first scent: who it is for, where it belongs, and what it should evoke.',action:'notebook'},
  {id:'history',title:'From incense to modern perfume',group:'Getting started',pages:[7,8],summary:'Follow the course’s overview of aromatic smoke, scented oils and modern compositions.',blocks:[
    ['Early aromatic traditions','The history chapter introduces fragrance through resins, herbs and woods used in ritual settings. Oils and balms provided another way to carry plant aromas. Later, scented accessories such as gloves and scarves became part of fragrance use.'],
    ['A changing palette','The course contrasts early natural materials with the combined natural and synthetic palette used in modern perfumery. Changes in extraction and manufacture expanded the scents available to perfumers.'],
    ['Artisan, designer and inspired fragrances','Artisan production emphasizes smaller batches and an individual creative approach. Designer products emphasize a recognizable, repeatable product. An inspired fragrance references another scent, while a counterfeit attempts to pass as another brand’s product. These are distinct ideas; packaging and scent similarity should not be confused.']],exercise:'Describe a fragrance memory without using a brand name. Note the materials or sensations you associate with it.'},
  {id:'nose',title:'Train your nose',group:'Aroma fundamentals',pages:[9],summary:'Connect scent with language, memory and changes over time.',blocks:[
    ['Make your own associations','Use a labeled scent strip and study one material at a time. Write the first associations that come to mind: an object, place, color, texture or memory. Your own descriptions help you build a repeatable scent vocabulary.'],
    ['Observe beyond the opening','Record the time and revisit the strip. Notice changes in intensity, sharpness, sweetness and the impression left behind. Use the same observation intervals when comparing trials.'],
    ['Compare, then describe','Compare two materials and identify what they share and where they differ. Short, specific descriptions are easier to use later than simply writing “nice” or “strong.” Take breaks between evaluations.']],exercise:'Choose two materials. Write three descriptors for each, then one similarity and one difference.',action:'notebook'},
  {id:'wheel',title:'Understand the fragrance wheel',group:'Aroma fundamentals',pages:[10,11,12,13],summary:'Use four broad families and fourteen subgroups to explore relationships.',blocks:[
    ['Families and subgroups','The course wheel groups aromas into Fresh, Floral, Oriental and Woody. In the app, the Oriental family is also labeled Amber so that you can recognize both terms. The subgroup names from the supplied wheel are preserved.'],
    ['Three ways to experiment','Try neighboring subgroups for shared qualities; compare opposite areas for contrast; or explore three areas spaced around the wheel. The course gives Citrus, Soft Floral and Woody Oriental as a triangular starting point. These are creative prompts, not guarantees of a balanced blend.'],
    ['A guide rather than a restriction','A material or accord can sit between groups, and classifications vary. Use the wheel to organize observations, then let trials show you whether a combination works. Add or remove one material at a time.']],exercise:'Select one family in Reference guides. Compare a neighboring family and a contrasting family on labeled strips.',action:'reference/wheel'},
  {id:'pyramid',title:'Top, heart and base notes',group:'Aroma fundamentals',pages:[13,14,15,16],summary:'Understand how a fragrance changes from opening to dry-down.',blocks:[
    ['Three overlapping roles','Top notes create the opening impression. Heart, or middle, notes develop the central character. Base notes contribute to the later dry-down. These roles describe a fragrance’s development rather than three completely separate stages.'],
    ['The course’s timing guide','The diagram gives 5–15 minutes for top notes, 20–60 minutes for middle notes and 5–6 hours for base notes. Treat those as the course’s illustrative ranges, not a promise for every ingredient or blend.'],
    ['The 30 / 50 / 20 starting point','The instructor suggests 30% top, 50% heart and 20% base as one creative starting point. It can help you plan a trial, but it is not mandatory and does not establish ingredient safety or finished-product concentration.']],exercise:'Compare the same blotter at several intervals. Record which impressions dominate at each point.',action:'reference/pyramid'},
  {id:'accords',title:'Develop an accord',group:'Aroma fundamentals',pages:[16],summary:'Move from a brief to strips, small blends and recorded proportions.',blocks:[
    ['Try the strip fan','Label a strip for each material. Hold selected strips together in a fan, then add or remove strips to explore combinations before committing them to a bottle. The result is a direction to test, not an exact prediction of a mixed formula.'],
    ['Build a small trial','The course suggests beginning with base materials, then adding heart and top materials in small additions. Keep a running record of every addition. Use a consistent measurement basis throughout a trial.'],
    ['Make the result repeatable','Give each formula a name and version. Record ingredient identities, stock dilutions, quantities and the date. When the trial is ready to revisit, compare the result with the original brief.']],exercise:'Open an artisan formula, load it into the notebook, and save a clearly named study version.',action:'formulas'},
  {id:'palette',title:'Build your perfumer’s palette',group:'Aroma fundamentals',pages:[16,17],summary:'Learn a manageable set of materials before expanding it.',blocks:[
    ['Start with materials you know','A large inventory is less useful than a smaller palette you can recognize and describe. Learn how each material behaves alone and in a few simple combinations. Expand when you can explain what a new material adds.'],
    ['Let the brief guide selection','Choose materials that support your intended mood and setting. Notice ingredients you repeatedly favor; these can become part of your creative style, but deliberate comparisons help you avoid repeating the same blend unintentionally.'],
    ['Record the actual product','A label such as Rose, Musk or Vanilla may describe many different materials or accords. Record the supplier’s product name and any dilution. A scent name alone is not enough to reproduce a formula precisely.']],exercise:'Make a palette list with the exact product name, dilution and three scent descriptors for every material you own.'},
  {id:'aromatics',title:'Natural and synthetic aromatics',group:'Materials & bases',pages:[18,19,20],summary:'Distinguish essential oils, absolutes, fragrance oils and aroma chemicals.',blocks:[
    ['Essential oils and absolutes','The course introduces essential oils as concentrated aromatic materials commonly obtained by distillation or expression. It describes absolutes through solvent extraction, with enfleurage included as historical context. Extraction method affects what is obtained and how it smells.'],
    ['Fragrance oils and aroma chemicals','A fragrance oil can be a mixture of natural and synthetic ingredients; it is not necessarily an essential oil diluted in a carrier. Aroma chemicals expand the palette beyond materials that can be conveniently extracted from plants.'],
    ['Choose by identity and purpose','Natural or synthetic origin does not by itself determine suitability for a product. Learn the actual material, its strength and its intended use. The professional recipe abbreviations are AA for aroma accord, AC for aroma chemical and EO for essential oil.']],exercise:'Pick one ingredient from a professional formula and identify what extra supplier information you would need to reproduce it.',action:'formulas'},
  {id:'carriers',title:'Choose a carrier',group:'Materials & bases',pages:[20,21,27,28],summary:'Compare alcohol, liquid oil and wax-based perfume formats.',blocks:[
    ['What the carrier does','The carrier dilutes and delivers the aromatic blend. Its composition influences how the product feels, how it is applied and how the aroma is released. Dilution alone does not establish that every ingredient is suitable at its final concentration.'],
    ['Alcohol and oil formats','The course contrasts an alcohol-based spray with an oil-based product applied more locally. It discusses perfumer’s alcohol and prepared perfume bases, and introduces jojoba, fractionated coconut and sunflower oils as oil-carrier examples.'],
    ['Read the base specification','Prepared bases can already contain water and other additives. Record their composition and supplier instructions before adding anything else. Household alcohol products are not interchangeable with a base formulated for perfumery.'],
    ['Wax-based formats','Solid perfume uses a wax/oil/butter structure. Texture and heat stability depend on the complete formulation. Changing the wax type may require changing the ratios as well.']],exercise:'Choose a format for your brief—spray, oil or solid—and list the base information you need before formulating.',action:'calculators'},
  {id:'fixatives',title:'Fixatives, projection and longevity',group:'Materials & bases',pages:[21,22],summary:'Separate formulation choices from what you perceive when wearing a scent.',blocks:[
    ['More than one factor','The course discusses fixatives alongside base-note selection, fragrance concentration and the carrier. A single additive is not a substitute for a well-developed composition, and increased concentration does not guarantee a particular wearing time.'],
    ['Describe the effect','When comparing a formula with and without an additive, record the opening, development, diffusion and dry-down. Keep the rest of the formula the same so the comparison is useful.'],
    ['Perception can change','The course describes olfactory accommodation: you may become less aware of a scent after sustained exposure. Use breaks and consistent comparison conditions rather than assuming that reduced awareness always means the fragrance has disappeared.']],exercise:'Compare two versions under the same conditions and describe the difference without assigning a guaranteed number of hours.'},
  {id:'concentration',title:'Perfume concentration names',group:'Materials & bases',pages:[22,23],summary:'Read the course’s splash, cologne, EDT, EDP and parfum ranges.',blocks:[
    ['The course ranges','The concentration chart lists Body Splash / Body Spray at 1–3%, Cologne at 4–7%, Eau de Toilette at 7–10%, Eau de Parfum at 10–20% and Parfum at 20–40%. These are the ranges taught in this course; naming conventions vary.'],
    ['Concentration and batch size','For a 50 mL batch at 20% fragrance by volume, the arithmetic gives 10 mL fragrance and 40 mL carrier. Record whether the percentage is by volume or by weight. Do not substitute grams for milliliters without material density information.'],
    ['A product name is not an ingredient limit','A concentration category describes the overall aromatic load. It does not determine whether each material meets the requirements for the intended finished product.']],exercise:'Use the concentration reference to compare the aromatic amount in the same bottle size at two different loads.',action:'reference/concentration'},
  {id:'equipment',title:'Set up your workbench',group:'Working methods',pages:[24],summary:'Prepare measuring tools, labeled containers and a record of every trial.',blocks:[
    ['Measuring and blending','The course lists glass pipettes or droppers, beakers or mixing vessels, scent strips and storage bottles. A suitable scale supports trials recorded by mass. Choose equipment appropriate to the material and the quantities being measured.'],
    ['Storage and packaging','Use compatible, clearly labeled containers. The course suggests amber or dark-blue glass for light-sensitive materials. Bottle style depends on the format: spray, roll-on or a container for solid perfume.'],
    ['Record keeping','Label ingredients, maturing blends and finished trials. Include the formula version and date. Keep a notebook of quantities and observations so that a result can be reproduced.']],exercise:'Prepare labels and a blank formula record before making a trial.',action:'notebook'},
  {id:'handling',title:'Handling and product checks',group:'Working methods',pages:[25,26],summary:'Use material-specific information alongside the course’s general precautions.',blocks:[
    ['A prepared workspace','The course emphasizes ventilation, avoiding ignition sources, using suitable protective equipment, closing containers and keeping materials away from children and animals. Use the supplier’s safety data sheet for the exact material and handling instructions.'],
    ['Product-specific limits','Check material identity, dilution and the intended product category. The IFRA guidance explains that quantitative restrictions apply to concentrations in the finished consumer product. A course blend or total fragrance percentage alone cannot establish conformity.'],
    ['Before commercial use','The course separates formulation practice from product safety, labeling and other requirements for sale. Requirements depend on the product and market; the app’s arithmetic and study recipes do not certify a finished product.']],links:[['IFRA: using the Standards','https://ifrafragrance.org/using-the-standards'],['IFRA Standards library','https://ifrafragrance.org/standards-library']],exercise:'Collect the supplier documentation for each material before deciding how a study blend could be used.'},
  {id:'base-recipe',title:'Read the homemade-base example',group:'Making products',pages:[28,29,30],summary:'Understand the listed components and the arithmetic issue in the course example.',blocks:[
    ['Components in the example','The source lists 1 L grain alcohol at 90% or higher, 10 mL Maskanol / dipropylene glycol, 10 mL isopropyl myristate and 10 mL fixative, with water discussed as optional. It calls these alcohol, solvent, dispersant and fixative. This is a source example, not a universal specification for a base.'],
    ['Check the total','Adding the three 10 mL components to 1,000 mL alcohol gives a nominal sum of 1,030 mL before optional water, not 1,000 mL. Actual mixture volume can also differ from the simple sum.'],
    ['A percentage inconsistency','The text refers to 10% water and also gives 10 mL per liter. Numerically, 10 mL is 1% of 1,000 mL, while 100 mL is 10%. The app does not silently choose one interpretation or use this example as an automatic preset.'],
    ['Work from a defined base','For a reproducible trial, use a defined composition and supplier instructions, then document every addition. The name “fixative” does not identify a unique material.']],exercise:'Write the example quantities in a table and calculate their nominal total. Mark the unspecified materials and conflicting percentages.'},
  {id:'liquid',title:'Plan a liquid perfume batch',group:'Making products',pages:[30],summary:'Move from a tested fragrance blend to a measured finished batch.',blocks:[
    ['Choose the fill amount','Decide the usable fill volume for the actual bottle and closure. The course uses a 100 mL bottle with a little headspace as an example; determine the fill for your packaging rather than assuming the nominal capacity is the fill amount.'],
    ['Calculate fragrance and carrier','Choose a documented concentration and consistent unit basis. Multiply the finished batch by the fragrance percentage, then subtract that quantity from the batch total to determine the carrier. The app’s liquid calculator works by volume.'],
    ['Record and revisit','The course describes combining the base and fragrance with slow stirring, then letting the finished mixture rest before evaluation. Record the base identity, formula version, fill amount and evaluation dates.']],exercise:'Calculate a 50 mL example at 20% by volume, then change the batch size to see how both quantities scale.',action:'calculators/perfume'},
  {id:'diffuser',title:'Read the reed-diffuser example',group:'Making products',pages:[30],summary:'Identify the components and check the total before scaling.',blocks:[
    ['The source’s three components','The ebook describes fragrance, dipropylene glycol and perfumer’s alcohol. It gives separate ranges of 30–40%, 50–65% and 5–10% respectively. Those ranges cannot be combined arbitrarily: the selected percentages must total 100%.'],
    ['Order described in the course','The course combines fragrance with dipropylene glycol, then adds the alcohol component. Suitability depends on the actual fragrance, base, reeds and supplier specifications. The source ranges are study material rather than a ready-made preset for every diffuser.'],
    ['The spreadsheet differs','The original diffuser spreadsheet contains a water field and an inconsistent percentage formula. The app calculates amount = batch × percentage / 100 and fills the remainder with the chosen diffuser base. It does not assume the spreadsheet and ebook describe the same composition.']],exercise:'Choose percentages that add to 100 as an arithmetic exercise, then list which material specifications would need checking.',action:'calculators/reed'},
  {id:'solid',title:'Understand solid perfume',group:'Making products',pages:[23,31,32],summary:'Explore a balm format and understand why the source recipe needs clarification.',blocks:[
    ['A balm format','The course presents solid perfume as a compact format made with fragrance, wax, oil and butter. The wax/oil balance controls texture. Heat exposure can soften or melt the product, so packaging and storage are part of the formulation decision.'],
    ['The original quantities','The recipe is described as making 15 g, but lists 2–3 mL fragrance, 9 g vegetable butter, 2 g beeswax and 5 mL vegetable oil. Because those are mixed units, the stated 15 g yield cannot be confirmed from the quantities without densities and clarification.'],
    ['What the practical lesson describes','The lesson melts the wax, butter and oil together, removes the mixture from heat, then adds fragrance during cooling before pouring. Use the temperature and compatibility guidance for the actual materials; the source’s temperature note is not a universal rule for all fragrances.'],
    ['A consistent calculator','The app uses grams for every component and percentages that total 100%. Its editable values are separate arithmetic examples, not a transcription of the mixed-unit source recipe.']],exercise:'Rewrite a trial as a complete mass-based formula once every material and percentage has been established.',action:'calculators/solid'},
  {id:'maturation',title:'Maturation and maceration',group:'Evaluate & refine',pages:[33,34],summary:'Distinguish resting the concentrate from resting the finished perfume.',blocks:[
    ['Before the base: maturation','The course uses “maturation” for resting a newly blended fragrance concentrate. It suggests a seven-day observation point in a sealed, labeled bottle stored away from light and heat. Record the initial impression and compare it at the chosen review point.'],
    ['After the base: maceration','The course uses “maceration” for the resting period after fragrance and base are combined. It describes several approaches, including four weeks in darkness. These are the instructor’s methods rather than a guaranteed timetable for every formula.'],
    ['Keep the trial reproducible','Record the container, start date, storage conditions and evaluation dates. The source also describes open-container and refrigeration cycles; these are not built into the app as procedures because solvent handling and equipment suitability require separate assessment.']],exercise:'Add the mixing date, initial observations and next review date to your trial record.',action:'notebook'},
  {id:'evaluation',title:'Evaluate fragrance quality',group:'Evaluate & refine',pages:[34,35,36,37],summary:'Separate scent development, performance and presentation.',blocks:[
    ['The perfumer’s questions','Assess whether the fragrance fits the brief, whether its materials feel balanced, how it evolves, and whether it offers something distinctive. Notice both the opening and the dry-down. A stable impression and an evolving one can each be intentional.'],
    ['Projection, sillage and longevity','Projection describes how far a scent radiates. Sillage is the trail left as someone moves. Longevity describes how long the scent remains perceptible. Record these separately instead of compressing them into a single “strength” score.'],
    ['Context and audience','The course asks about season, occasion, time of day and the intended wearer. Feedback can differ because preferences and perception differ. Compare trials under similar conditions and document the context.'],
    ['Presentation and perceived value','Bottle, closure, packaging, branding and price affect the experience of a product. Evaluate these separately from the blend itself so that attractive packaging does not hide a formulation issue.']],exercise:'Write separate observations for opening, heart, dry-down, projection, longevity and fit with your brief.',action:'notebook'},
  {id:'mods',title:'Modify, compare and scale',group:'Evaluate & refine',pages:[38],summary:'Keep successive versions so each change teaches you something.',blocks:[
    ['Make a new version','The course calls a development version a MOD. Save the previous version before changing ingredients or quantities. Name each trial clearly so you can compare it with the exact earlier formula.'],
    ['Change deliberately','Compare one or a few controlled changes rather than changing everything at once. A blend can also behave differently at a different finished-product concentration, so record that variable too.'],
    ['Scale after evaluation','Once you have selected a version, scale every ingredient by the same factor. Preserve the measurement basis: the artisan ebook uses drops, professional formulas use milliliters, and a mass-based formula uses grams. Scaling ratios does not convert between these units.']],exercise:'Load a course formula, save it as “v1,” then create a separately named experiment and compare the two.',action:'formulas'},
  {id:'photography',title:'Photograph your creations',group:'Presentation',pages:[39,40],summary:'Use light, background and composition to show the bottle clearly.',blocks:[
    ['Start with the product','Choose a clean bottle and legible label. Study examples for ideas about composition, then choose a background that supports your own product. Paper, ceramic, foliage or a simple wall can provide useful textures.'],
    ['Control the light','Use soft natural light or a suitable diffused artificial light. Observe reflections on glass and highlights on the label. Change the position of the light or bottle before relying on editing.'],
    ['Explore angles and detail','Try a straight-on view, an overhead composition and a close detail of the label or closure. Props should support the scent story without obscuring the product.'],
    ['Edit lightly','Adjust exposure, color and distracting reflections while preserving an honest view of the bottle and product. Keep a consistent style across a set of photos.']],exercise:'Photograph one bottle against two backgrounds and compare readability, reflections and mood.'}
];

export const families = [
  {name:'Floral',group:'Floral',color:'#efa6c5',description:'Flower-centered impressions, from bright and fresh to richer floral compositions.',examples:'Rose, lily impressions',pair:'Soft Floral or Fruity'},
  {name:'Soft Floral',group:'Floral',color:'#dfafd7',description:'Gentle, powdery floral impressions in the course classification.',examples:'Powdery floral accords',pair:'Floral or Floral Oriental'},
  {name:'Floral Oriental',group:'Amber / Oriental',color:'#cba0e2',description:'Floral freshness combined with the warmer, sweeter character of the amber family.',examples:'Orange blossom and sweet-spice impressions',pair:'Soft Floral or Soft Oriental'},
  {name:'Soft Oriental',group:'Amber / Oriental',color:'#b29bdf',description:'A lighter interpretation of the warm amber family.',examples:'Frankincense, star-anise impressions in the course',pair:'Floral Oriental or Oriental'},
  {name:'Oriental',group:'Amber / Oriental',color:'#b789c4',description:'Rich, warm, sweet, resinous or spicy impressions. Often called amber in other classifications.',examples:'Vanilla, resins, cinnamon',pair:'Soft Oriental or Woody Oriental'},
  {name:'Woody Oriental',group:'Amber / Oriental',color:'#bf956f',description:'Warm amber qualities combined with earthy and woody weight.',examples:'Patchouli, sandalwood',pair:'Oriental or Woods'},
  {name:'Woods',group:'Woody',color:'#c6a673',description:'Warm wood-centered impressions that can give a composition depth.',examples:'Wood accords',pair:'Woody Oriental or Mossy Woods'},
  {name:'Mossy Woods',group:'Woody',color:'#89b78b',description:'Green, mossy and woody impressions. The course text inconsistently calls this “Musk”; the supplied wheel labels it Mossy Woods.',examples:'Mossy wood accords',pair:'Woods or Dry Woods'},
  {name:'Dry Woods',group:'Woody',color:'#b39274',description:'Drier wood impressions contrasted with softer floral areas of the wheel.',examples:'Dry wood accords',pair:'Mossy Woods or Aromatic'},
  {name:'Aromatic',group:'Fresh',color:'#9e9be3',description:'Herbal and aromatic impressions, also called herbal in the course.',examples:'Lavender and aromatic herbs',pair:'Dry Woods or Citrus'},
  {name:'Citrus',group:'Fresh',color:'#efce6d',description:'Bright, fresh citrus impressions used to lift a composition.',examples:'Orange, bergamot, lemon',pair:'Aromatic or Water'},
  {name:'Water',group:'Fresh',color:'#79c9e4',description:'Aquatic and marine impressions that evoke water, ocean air or seaweed.',examples:'Marine and aquatic accords',pair:'Citrus or Green'},
  {name:'Green',group:'Fresh',color:'#83cd99',description:'Fresh leafy or green impressions, sometimes with a woody edge.',examples:'Galbanum',pair:'Water or Fruity'},
  {name:'Fruity',group:'Fresh',color:'#f29b9d',description:'Rounded fruit impressions, often sweeter than the citrus subgroup.',examples:'Apple, pear, peach, strawberry and tropical-fruit accords',pair:'Green or Floral'}
];
export const concentrations = [['Body Splash / Body Spray',1,3],['Cologne',4,7],['Eau de Toilette',7,10],['Eau de Parfum',10,20],['Parfum',20,40]];
