const $=s=>document.querySelector(s);
const shelf=$('#course-library');
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=n=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.ceil(n/1024)} KB`;
let items=[],filter='All',current=null,page=1,opener=null,request=0;
shelf.innerHTML=`<div class="shelf-heading"><div><span class="eyebrow">YOUR COMPLETE COLLECTION</span><h2>Course library</h2></div><span id="library-count" class="pill">Loading files…</span></div><div class="library-tools"><label>Find a course file<input id="library-search" type="search" placeholder="Search ebooks, fragrance wheel, calculators…"></label><div class="library-filters" role="group" aria-label="File category">${['All','Ebooks','Guides & printables','Calculators','Images'].map((n,i)=>`<button class="secondary" data-filter="${n}" aria-pressed="${i===0}">${n}</button>`).join('')}</div></div><p id="library-status" role="status"></p><div id="resource-grid"></div>`;
const dialog=document.createElement('dialog');dialog.id='resource-reader';dialog.innerHTML=`<div class="reader-header"><div><span id="reader-meta" class="eyebrow"></span><h2 id="reader-title"></h2></div><button id="reader-close" class="secondary" aria-label="Close reader">✕</button></div><div class="reader-toolbar"><div id="page-controls"><button id="page-prev" class="secondary" aria-label="Previous page">←</button><label>Page <input id="reader-page" type="number" min="1" value="1" aria-label="Page number"></label><span id="page-total"></span><button id="page-next" class="secondary" aria-label="Next page">→</button></div><div class="reader-links"><button id="reader-zoom" class="secondary" aria-pressed="false">Zoom in</button><a id="reader-original" class="secondary" target="_blank" rel="noopener">Open original</a><a id="reader-download" class="primary" download>Download</a></div></div><p id="reader-note" class="small"></p><div id="reader-content"></div>`;dialog.setAttribute('aria-labelledby','reader-title');document.body.append(dialog);
function render(){const q=$('#library-search').value.toLowerCase().trim();const shown=items.filter(i=>(filter==='All'||i.category===filter)&&`${i.title} ${i.filename} ${i.folder} ${i.format}`.toLowerCase().includes(q));$('#library-count').textContent=`${items.length} files`;$('#library-status').textContent=`${shown.length} ${shown.length===1?'file':'files'}${q?' matching your search':''}`;$('#resource-grid').innerHTML=shown.map(i=>`<article class="resource-card"><button class="resource-open" data-id="${i.id}" aria-label="Open ${safe(i.title)}"><div class="resource-cover ${i.thumbnail?'':'file-cover'}">${i.thumbnail?`<img src="${i.thumbnail}" alt="" loading="lazy">`:`<span>${i.format==='XLSX'||i.format==='NUMBERS'?'▦':'▤'}</span>`}<span class="format-badge">${i.format}</span></div><div class="resource-info"><span class="tag">${i.category}</span><h3>${safe(i.title)}</h3><p>${i.pageCount?`${i.pageCount} pages · `:''}${size(i.size)}${i.folder!=='.'?` · ${safe(i.folder)}`:''}</p><span class="resource-action">${i.pages?'Read in app':i.spreadsheet?'Preview spreadsheet':i.category==='Images'?'View image':'View file'} <span aria-hidden="true">↗</span></span></div></button></article>`).join('')||'<p class="small">No files found. Try a different search or category.</p>';}
$('#library-search').oninput=render;shelf.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;shelf.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));render();});
shelf.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)open(items.find(i=>i.id===b.dataset.id),b);});
function renderPage(){const content=$('#reader-content');content.classList.remove('spreadsheet-content');content.innerHTML=`<img class="document-page" src="${current.pages[page-1]}" alt="${safe(current.title)}, page ${page}">`;$('#reader-page').value=page;$('#page-total').textContent=`of ${current.pages.length}`;$('#page-prev').disabled=page===1;$('#page-next').disabled=page===current.pages.length;content.scrollTop=0;}
function move(n){if(!current?.pages)return;page=Math.max(1,Math.min(current.pages.length,n));renderPage();}
async function open(item,button){current=item;opener=button;page=1;const token=++request;$('#reader-title').textContent=item.title;$('#reader-meta').textContent=`${item.format} · ${size(item.size)}`;$('#reader-note').textContent=item.readerNote||'';$('#reader-original').href=item.url;$('#reader-download').href=item.url;$('#reader-download').download=item.filename;$('#page-controls').hidden=!item.pages;$('#reader-zoom').hidden=!item.pages&&item.category!=='Images';$('#reader-page').max=item.pageCount||1;$('#reader-content').className='';$('#reader-zoom').textContent='Zoom in';$('#reader-zoom').setAttribute('aria-pressed','false');$('#reader-content').replaceChildren();dialog.showModal();document.body.classList.add('reader-open');
if(item.pages)renderPage();
else if(item.category==='Images')$('#reader-content').innerHTML=`<img class="document-page" src="${item.url}" alt="${safe(item.title)}">`;
else if(item.spreadsheet){$('#reader-content').textContent='Loading spreadsheet…';try{const r=await fetch(item.spreadsheet);if(!r.ok)throw Error();const sheets=await r.json();if(token!==request)return;$('#reader-note').textContent='Read-only preview of the original worksheet. Formula cells show saved results when available; use the app calculators for live calculations.';$('#reader-content').className='spreadsheet-content';$('#reader-content').innerHTML=sheets.map(s=>`<section class="sheet-preview"><h3>${safe(s.title)}</h3><table><thead><tr><th>Cell</th><th>Value</th><th>Original formula</th></tr></thead><tbody>${s.rows.flat().map(c=>`<tr><td>${safe(c.cell)}</td><td>${safe(c.value)}</td><td><code>${safe(c.formula||'')}</code></td></tr>`).join('')}</tbody></table></section>`).join('');}catch{if(token===request)$('#reader-content').textContent='Preview could not load. You can still download the original spreadsheet.';}}
else $('#reader-content').innerHTML='<div class="reader-empty"><span>▦</span><h3>Apple Numbers workbook</h3><p>Download this original workbook and open it in Numbers. For a preview here, choose its Windows or GoogleDocs XLSX edition in the library.</p></div>';
}
$('#reader-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{request++;document.body.classList.remove('reader-open');$('#reader-content').replaceChildren();opener?.focus();});
$('#page-prev').onclick=()=>move(page-1);$('#page-next').onclick=()=>move(page+1);$('#reader-page').onchange=e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=current.pages.length)move(n);else e.target.value=page;};$('#reader-zoom').onclick=()=>{const on=$('#reader-content').classList.toggle('zoomed');$('#reader-zoom').setAttribute('aria-pressed',on);$('#reader-zoom').textContent=on?'Fit page':'Zoom in';};dialog.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='ArrowRight'){e.preventDefault();move(page+1);}if(e.key==='ArrowLeft'){e.preventDefault();move(page-1);}});
try{const r=await fetch('library.json');if(!r.ok)throw Error();items=(await r.json()).items;render();}catch{$('#library-status').textContent='The course library could not load. Refresh the page to try again.';$('#library-count').textContent='Unavailable';}
